### ISSUE TITLE
Automatic selection of the maximum fluctuation peak

### ISSUE THREAD

**Issue by danielemichilli** [danielemichilli/DM_phase#4]
Currently, the code finds the fluctuation band where the largest power is present.
It should instead find the peak with the largest fluctuation possible to identify.

**Comment by aseymourGBT** [comment]
Currently, the code finds the fluctuation band where the largest power is
present.
It should instead find the peak with the largest fluctuation possible to
identify.

-Not sure what we want to do here. The max power just says that a feature
of certain scale it is in more channels, and with the drifting, this can
peak at large scales but not at right DM. Really we want to focus on the
power at the highest fluctuation frequencies and ignore the rest. This
varies greatly from burst to burst. I think using the w^2 weighting is the
most logical for now.

-AS
